adaptive-controller-config:
  densification-view-space-position-gradients-threshold: 0.0000008
  gaussian-split-factor-phi: 1.6
  num-iterations-densify: 100
  num-iterations-reset-alpha: 4000
  num-iterations-warm-up: 500
  reset-alpha-value: -2.
  transparent-alpha-threshold: -2.
  under-reconstructed-s-threshold: 0.03 # the same unit as the point cloud
  floater_threshold: 3. # shall not rely on floater points removal too much, otherwise we will stuck in the remove large point->increase points loop, and finally remove all points
gaussian-point-cloud-scene-config:
  max-num-points-ratio: 100.
  num-of-features: 56
increase-color-max-sh-band-interval: 1000.0
log-image-interval: 1000
log-loss-interval: 10
log-metrics-interval: 100
enable_taichi_kernel_profiler: True
log_taichi_kernel_profile_interval: 3000
loss-function-config:
  lambda-value: 0.2
  enable_regularization: True
  regularization_weight: 0.5
num-iterations: 300000
pointcloud-parquet-path: 'data/boots_super_sparse/point_cloud.parquet'
rasterisation-config:
  depth-to-sort-key-scale: 100.0
  far-plane: 1000.0
  near-plane: 0.001
summary-writer-log-dir: logs/boots_super_sparse_experiment
train-dataset-json-path: 'data/boots_super_sparse/boots_train.json'
val-dataset-json-path: 'data/boots_super_sparse/boots_val.json'
val-interval: 1000
