adaptive-controller-config:
  densification-view-space-position-gradients-threshold: 0.00001
  gaussian-split-factor-phi: 1.6
  num-iterations-densify: 100
  num-iterations-reset-alpha: 300000
  num-iterations-warm-up: 1000
  reset-alpha-value: -2.0
  transparent-alpha-threshold: -3.
  under-reconstructed-s-threshold: 0.05
  floater_threshold: 3.0
gaussian-point-cloud-scene-config:
  max-num-points-ratio: 1.2
  num-of-features: 56
increase-color-max-sh-band-interval: 1000.0
log-image-interval: 1000
log-loss-interval: 10
log-metrics-interval: 100
loss-function-config:
  lambda-value: 0.2
num-iterations: 300000
pointcloud-parquet-path: 'data/kitti/point_cloud.parquet'
rasterisation-config:
  depth-to-sort-key-scale: 100.0
  far-plane: 1000.0
  near-plane: 0.1
summary-writer-log-dir: logs/sigmoid_on_image_fix_bug_remove_floater_tune_3
train-dataset-json-path: 'data/kitti/kitti_train.json'
val-dataset-json-path: 'data/kitti/kitti_val.json'
val-interval: 30000
